// Generated by gencpp from file first_project/Reset_odomResponse.msg
// DO NOT EDIT!


#ifndef FIRST_PROJECT_MESSAGE_RESET_ODOMRESPONSE_H
#define FIRST_PROJECT_MESSAGE_RESET_ODOMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_project
{
template <class ContainerAllocator>
struct Reset_odomResponse_
{
  typedef Reset_odomResponse_<ContainerAllocator> Type;

  Reset_odomResponse_()
    : resetted(false)  {
    }
  Reset_odomResponse_(const ContainerAllocator& _alloc)
    : resetted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _resetted_type;
  _resetted_type resetted;





  typedef boost::shared_ptr< ::first_project::Reset_odomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_project::Reset_odomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Reset_odomResponse_

typedef ::first_project::Reset_odomResponse_<std::allocator<void> > Reset_odomResponse;

typedef boost::shared_ptr< ::first_project::Reset_odomResponse > Reset_odomResponsePtr;
typedef boost::shared_ptr< ::first_project::Reset_odomResponse const> Reset_odomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_project::Reset_odomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_project::Reset_odomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_project::Reset_odomResponse_<ContainerAllocator1> & lhs, const ::first_project::Reset_odomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.resetted == rhs.resetted;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_project::Reset_odomResponse_<ContainerAllocator1> & lhs, const ::first_project::Reset_odomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_project::Reset_odomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_project::Reset_odomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_project::Reset_odomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_project::Reset_odomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_project::Reset_odomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_project::Reset_odomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_project::Reset_odomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "018a2998f38d6a4605b80747930e74ce";
  }

  static const char* value(const ::first_project::Reset_odomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x018a2998f38d6a46ULL;
  static const uint64_t static_value2 = 0x05b80747930e74ceULL;
};

template<class ContainerAllocator>
struct DataType< ::first_project::Reset_odomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_project/Reset_odomResponse";
  }

  static const char* value(const ::first_project::Reset_odomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_project::Reset_odomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool resetted\n"
;
  }

  static const char* value(const ::first_project::Reset_odomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_project::Reset_odomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resetted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Reset_odomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_project::Reset_odomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_project::Reset_odomResponse_<ContainerAllocator>& v)
  {
    s << indent << "resetted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resetted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PROJECT_MESSAGE_RESET_ODOMRESPONSE_H
