// Generated by gencpp from file first_project/Reset_odomRequest.msg
// DO NOT EDIT!


#ifndef FIRST_PROJECT_MESSAGE_RESET_ODOMREQUEST_H
#define FIRST_PROJECT_MESSAGE_RESET_ODOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_project
{
template <class ContainerAllocator>
struct Reset_odomRequest_
{
  typedef Reset_odomRequest_<ContainerAllocator> Type;

  Reset_odomRequest_()
    {
    }
  Reset_odomRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::first_project::Reset_odomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_project::Reset_odomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Reset_odomRequest_

typedef ::first_project::Reset_odomRequest_<std::allocator<void> > Reset_odomRequest;

typedef boost::shared_ptr< ::first_project::Reset_odomRequest > Reset_odomRequestPtr;
typedef boost::shared_ptr< ::first_project::Reset_odomRequest const> Reset_odomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_project::Reset_odomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_project::Reset_odomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace first_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_project::Reset_odomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_project::Reset_odomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_project::Reset_odomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_project::Reset_odomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_project::Reset_odomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_project::Reset_odomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_project::Reset_odomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::first_project::Reset_odomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::first_project::Reset_odomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_project/Reset_odomRequest";
  }

  static const char* value(const ::first_project::Reset_odomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_project::Reset_odomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::first_project::Reset_odomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_project::Reset_odomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Reset_odomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_project::Reset_odomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::first_project::Reset_odomRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PROJECT_MESSAGE_RESET_ODOMREQUEST_H
